### ISSUE TITLE
'mars-gen' breaks when installed from vendored directory

### ISSUE THREAD

**Issue by ipoerner** [roblillack/mars#5]
Installing `mars-gen` from within a vendored directory with all other dependencies pre-vendored:

```
$ go install ${PACKAGE}/vendor/github.com/roblillack/mars/cmd/mars-gen
```

The `mars-gen` binary is generated alright; however, code generation fails:

```
$ mars-gen register-controllers app/controllers
2016/10/27 07:40:57 reflect.go:308: Failed to find import path for mars.Controller
$ cat app/controllers/register_controllers.gen.go 
// DO NOT EDIT -- code generated by mars-gen
package controllers

import (
	"reflect"
	"github.com/roblillack/mars"
)

var (
	// So compiler won't complain if the generated code doesn't reference reflect package...
	_ = reflect.Invalid
)

func RegisterControllers() {
	
}
```

```
$ mars-gen reverse-routes -o app/routes/routes.gen.go app/controllers
2016/10/27 07:41:05 reflect.go:308: Failed to find import path for mars.Controller
$ cat app/routes/routes.gen.go 
// DO NOT EDIT -- code generated by mars-gen
package routes

import (
	"github.com/roblillack/mars"
)


```

Currently, this can only be solved by also adding a copy of Mars to the user's `$GOPATH`. Somehow feels like turning the concept of a vendored dependency upside down, though.

**Comment by ipoerner** [comment]
As a sidenote, even when there's a copy of Mars in the `$GOPATH`, calling `mars-gen` would only work when called from the root directory of my application, but not from within the `app/` folder.

**Comment by roblillack** [comment]
Hey @ipoerner, are you able to run something along the lines of

```
go run ../vendor/github.com/roblillack/mars/cmd/mars-gen/{main,reflect}.go register-controllers ./controllers
```

from your app directory?

**Comment by ipoerner** [comment]
Yes, thanks, that works fine. But quite honestly, it's not something I'd want to write as a 'generate' directive.

**Comment by roblillack** [comment]
Yeah, sure. Just wanted to get a better understanding of what might be wrong.
